version: "3.9"

services:
  web:
    build:
      context: .
    env_file:
      - .env.docker
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
    command: npm run start

  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-calendarsync}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-calendarsync}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
