version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    env_file:
      - .env.docker
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "3000:3000"
    volumes:
      # Mount source code for hot reloading
      - ./:/app
      
      # Exclude node_modules and build artifacts
      - /app/node_modules
      - /app/.next
      
      # Use named volumes for persistence
      - node_modules:/app/node_modules
      - next_cache:/app/.next
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    command: sh -c "npx prisma generate && npm run dev"

  db:
    image: postgres:15-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-calendarsync}
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-calendarsync}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
  node_modules:
  next_cache:

